version: ~> 1.0

os: linux
dist: bionic

services:
  - docker

branches:
  only:
    - master
    - staging
    - release

language: node_js

cache:
  directories:
    - .cache
    - docker_images

env:
  - DOCKER_COMPOSE_VERSION=1.27.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

install:
  - echo ''

before_script:
  - cp .env.example .env

script:
  - make docker-dev
  - mkdir -p .out
  - mv .build/Release/packages/nextalign_cli/nextalign_cli .out/nextalign_Linux_x86_64

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "nextalign-release-bot"
  - git config --local user.email "nextalign-release-bot@nextstrain.org"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
   - provider: releases
     repo: neherlab/nextalign
     cleanup: false
     overwrite: true
     file:
       - .out/nextalign_Linux_x86_64
     on:
       all_branches: true
       condition: $TRAVIS_BRANCH =~ ^(master|staging|release)$
