version: '3.7'

services:
  nextalign_prod:
    container_name: nextalign_prod
    image: nextalign_prod
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER=user
        - GROUP=user
        - UID=$UID
        - GID=$GID
    command: 'make prod'
    volumes:
      - ./:/src
      - ./.cache/docker/home/user/.conan/data:/home/user/.conan/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-256color
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true
