version: 2.1

jobs:
  build:
    resource_class: medium

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - restore_cache:
          name: 'Restore caches'
          keys:
            - cache-nextalign-v1-docker_images
            - cache-nextalign-v1-cache

      - run:
          name: 'Build "Builder" container image'
          command: |
            make docker-cache-load
            make docker-prod-build
            make docker-cache-save

      - save_cache:
          name: 'Save docker image cache'
          key: cache-nextalign-v1-docker_images
          paths:
            - docker_images

      - run:
          name: 'Run "Builder" container image'
          command: |
            make docker-prod-run
            make output-prod

      - save_cache:
          name: 'Save build cache'
          key: cache-nextalign-v1-cache
          paths:
            - .cache

      - store_artifacts:
          name: 'Store Linux x86_64 binary'
          path: .out/nextalign_Linux_x86_64
          destination: nextalign_Linux_x86_64

      - run:
          name: "Publish Release on GitHub"
          command: |
            GHR_VERSION=0.13.0
            pushd ${HOME} && curl -fSL "https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz" | tar -xz --directory="$(pwd)" --strip-components=1 "ghr_v${GHR_VERSION}_linux_amd64/ghr"; popd
            VERSION=$(.out/nextalign_Linux_x86_64 --version)
            ${HOME}/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} .out/
