version: 2.1

jobs:
  build:
    resource_class: medium

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - restore_cache:
          name: 'Restore caches'
          keys:
           - cache-nextalign-v1-docker_images
           - cache-nextalign-v1-cache

      - run:
          name: 'Build "Builder" container image'
          command: |
            make docker-cache-load
            make docker-prod-build
            make docker-cache-save

      - save_cache:
          name: 'Save docker image cache'
          key: cache-nextalign-v1-docker_images
          paths:
            - docker_images

      - run:
          name: 'Run "Builder" container image'
          command:
            make docker-prod-run

      - save_cache:
          name: 'Save build cache'
          key: cache-nextalign-v1-cache
          paths:
            - .cache
